name: Release

permissions:
  contents: write
on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      release_url: ${{ steps.create-release.outputs.release-url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ github.ref_name }}

  build_and_upload:
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build econfixer
        run: |
          if "${{ matrix.os }}" == "windows-latest"; then
            go build -o econfixer.exe .
          else
            go build -o econfixer .
          fi

      - name: Upload binaries to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: econfixer*
          asset_name: econfixer-${{ matrix.os == 'windows-latest' && 'win' || '' }}${{ matrix.os != 'windows-latest' && (matrix.os == 'macos-latest' && 'darwin' || '') }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true